### ISSUE TITLE
MinterState isn't requirable by implementors.

### ISSUE THREAD

**Issue by tpendragon** [projecthydra-labs/active_fedora-noid#29] opened 2016-07-01 22:14 UTC
Makes production deploys fail.

**Comment by atz** [comment] 2016-07-01 22:53
Is requirable in engine_cart's `.internal_test_app`.  Probably related to whether the consumer has run `rails generate active_fedora:noid:install` (as the test app does), is a rails app/engine, etc.  

Anything else you can say about your production context that might contribute?  Or how to reproduce deterministically in a test?  Maybe a separate run of non-engine_cart specs without loading the test app?  Then a full pass inside the test app?  

Note: 2.x version is currently a beta release.

**Comment by atz** [comment] 2016-07-07 01:02
@mjgiarlo This is an entanglement of having the ActiveRecord and non-AR code in the same gem.  The consumer of the Noid PORO know what they want and don't expect to have to do any generation/installation.  The consumers of the AR MinterState presumably also know what they want, but can be expected to do generation/installation.  Probably there is some magic we can use to autoload only under certain conditions (`defined? ActiveRecord` doesn't seem good enough, since a rails app may just want the PORO).  So I'm not sure how much is wise to employ.  

More particularly, we can separate the test suite components, but I'm unsure there is any clean way to invoke, say, Part A without engine_cart, then everything inclusive of Part A (again) with engine_cart, in the same test run.  I can do it with an ENV in travis and 2 separate runs, but don't see how to get it in one.

**Comment by mjgiarlo** [comment] 2016-07-07 01:33
In the meantime, perhaps we'd best pin our stack to AF::Noid < 2 while we work this out.

**Comment by mjgiarlo** [comment] 2016-07-07 01:37
Or, alternatively, if that change should have necessitated a CC 2.0.0 release?

**Comment by atz** [comment] 2016-07-07 02:08
That change is in an AF::Noid **beta**.  Nobody should be using it in production, now or ever.  

Certainly I think some docs (here) about running the installer would be useful, at least to the AR consumer.  But the main question is whether a PORO will be able to still use the same gem without any additional requirements (and how to test that is true).

**Comment by tpendragon** [comment] 2016-07-18 18:55
The generator doesn't run (complains about expand_path?) and copying the migrations over manually and running it doesn't seem to let it run in prod. :(

**Comment by tpendragon** [comment] 2016-07-18 19:04
@atz Does someone have a production app with beta AF::Noid? Because even in CC's internal_app I can't get a MinterState object.

**Comment by atz** [comment] 2016-07-25 17:35
Again: nobody should be using a beta in production.  I'm unaware of anyone who is.  That being said, I would appreciate more detail about the generator not running.  That would be a dealbreaker.  

I agree that complication might come from retrofitting an engine on an existing gem.  My initial instinct was to make a separate gem.

**Comment by atz** [comment] 2016-07-29 23:53
@mjgiarlo need direction on this.  In particular, consider the problem of testing with engine cart and simultaneously without it.

**Comment by mjgiarlo** [comment] 2016-08-01 23:06
I'll do some testing this week or not long after.

**Comment by val99erie** [comment] 2016-10-18 21:12
Regarding @tpendragon 's comment about how to make it deterministic:  You can reproduce the problem using the test app that is generated by engine_cart in curation_concerns.  (Note that the problem only shows up in production mode)

In the curation_concerns workspace:
* `bundle exec rake engine_cart:generate`
* `cd .internal_test_app`
* Edit `config/secrets.rb` to add a secret_key_base in the `production` section
* `RAILS_ENV=production bin/rails c`

See also:
https://github.com/projecthydra/curation_concerns/issues/1045

**Comment by mjgiarlo** [comment] 2016-10-19 17:06
This is addressed in projecthydra/curation_concerns#1061 (WIP).

**Comment by mjgiarlo** [comment] 2016-10-21 03:05
Problem is in how CC requires AF::Noid. Closing.

**Closed by mjgiarlo** 2016-10-21 03:05 UTC
